"""Add level column to users

Revision ID: 9406d389dbd3
Revises: 121b2d2c645e
Create Date: 2025-07-08 00:35:27.780489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9406d389dbd3'
down_revision: Union[str, Sequence[str], None] = '121b2d2c645e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('complexity_level', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('ai_suggested_min_price', sa.DECIMAL(precision=10, scale=2), nullable=True))
    op.add_column('tasks', sa.Column('ai_suggested_max_price', sa.DECIMAL(precision=10, scale=2), nullable=True))
    op.add_column('tasks', sa.Column('ai_analysis_data', sa.JSON(), nullable=True))
    op.add_column('tasks', sa.Column('ai_analyzed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('level', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'level')
    op.drop_column('tasks', 'ai_analyzed_at')
    op.drop_column('tasks', 'ai_analysis_data')
    op.drop_column('tasks', 'ai_suggested_max_price')
    op.drop_column('tasks', 'ai_suggested_min_price')
    op.drop_column('tasks', 'complexity_level')
    # ### end Alembic commands ###
